version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/ssr
permissions:
  - object: /home/ubuntu/ssr
    owner: ubuntu
    group: ubuntu 
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ubuntu
