name: Build and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_GA_MEASURE_ID: ${{ secrets.NEXT_PUBLIC_GA_MEASURE_ID }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Zipping project
        run: |
          zip -r ${{ github.sha }}.zip .next scripts appspec.yml package.json package-lock.json

      - name: Deploy to S3
        run: aws s3 cp ./${{ github.sha }}.zip s3://narumir-io-code-store/blog-frontend/${{ github.sha }}.zip

      - name: Deploy Via Codedeploy
        run: |
          aws deploy create-deployment \
            --application-name blog \
            --deployment-group-name deploy_frontend \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=narumir-io-code-store,bundleType=zip,key=blog-frontend/${{ github.sha }}.zip
