name: Build and deply

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Configure Cloudflare R2 credentials
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_R2_API_TOKEN }}

      - name: Deploy Assets to Cloudflare R2
        working-directory: .static
        run: wrangler r2 object put blog-static/ --file=.

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Zipping lambda source code
        working-directory: .dist
        run: zip -r blog_ssr.zip .

      - name: Upload lambda source code
        working-directory: .dist
        run: aws s3 cp ./blog_ssr.zip s3://${{ secrets.AWS_S3_BUCKET }}/blog_ssr.zip

      - name: Deploy lambda source code
        run: aws lambda update-function-code --no-cli-pager --function-name blog_ssr --s3-bucket ${{ secrets.AWS_S3_BUCKET }} --s3-key blog_ssr.zip
