name: Build and release

on: [push]

jobs:
  release:
    name: Build and deploy
    runs-on: ubunut-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

