name: Build and release

on: [push]

jobs:
  release:
    name: Release pushed tag
    runs-on: ubunut-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

